from .bili import BilibiliNetworkCapture, extract_text_from_json_responses
from .douyin import DouyinNetworkCapture, extract_captions_from_json_responses
from .xiaohongshu import XiaohongshuNetworkCapture, extract_tags_from_json_responses
from .zhihu import ZhihuNetworkCapture